spring.application.name=bankapp
spring.datasource.url=jdbc:mysql://localhost:3306/sskm0116db?serverTimezone=UTC
spring.datasource.username=sskm0116
spring.datasource.password=thdqhdrms

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
